
import ThemeProvider from './providers'
import "./globals.css";


export const metadata = {
  title: 'Photos Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,  }) {
  return (
    <html lang="en">
      <body className='body'> 

        <ThemeProvider>


          {children}


        </ThemeProvider>

        </body>
    </html>
  )
}
